name: Build APK (Fork)

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Build flavor (alpha or meta)'
        required: false
        default: 'alpha'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
          go-version: '1.26'
          cache-dependency-path: |
            core/src/main/golang/go.sum
            core/src/foss/golang/go.sum

      - name: Apply Patches
        run: |
          cd $(go env GOROOT)
          for p in $GITHUB_WORKSPACE/.github/patch/*.patch; do patch --verbose -p 1 < "$p"; done

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('core/src/main/golang/go.sum', 'core/src/foss/golang/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Debug Build
        run: ./gradlew --no-daemon app:assemble${{ inputs.flavor }}Debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ inputs.flavor }}
          path: app/build/outputs/apk/**/**/*.apk
